/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:15:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Actions entity stored in table Actions. This class is a
 * "record entity" without JPA links.
 * 
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name = "Actions", catalog = "db_assigment")
public class Actions implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "Action_Code", nullable = false)
	private Integer actionCode;
	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "Action_Description", length = 45)
	private String actionDescription;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public Actions() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setActionCode(Integer actionCode) {
		this.actionCode = actionCode;
	}

	public Integer getActionCode() {
		return this.actionCode;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : Action_Description (VARCHAR)
	public void setActionDescription(String actionDescription) {
		this.actionDescription = actionDescription;
	}

	public String getActionDescription() {
		return this.actionDescription;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(actionCode);
		sb.append(actionDescription);
		return sb.toString();
	}
}