/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:15:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for ChargeCodes entity stored in table Charge_Codes. This
 * class is a "record entity" without JPA links.
 * 
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name = "Charge_Codes", catalog = "db_assigment")
public class ChargeCodes implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "Charge_Code", nullable = false)
	private Integer chargeCode;
	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "Charge_Description", length = 45)
	private String chargeDescription;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public ChargeCodes() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setChargeCode(Integer chargeCode) {
		this.chargeCode = chargeCode;
	}

	public Integer getChargeCode() {
		return this.chargeCode;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : Charge_Description (VARCHAR)
	public void setChargeDescription(String chargeDescription) {
		this.chargeDescription = chargeDescription;
	}

	public String getChargeDescription() {
		return this.chargeDescription;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(chargeCode);
		sb.append(chargeDescription);
		return sb.toString();
	}
}