/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:15:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Customers entity stored in table Customers.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="Customers", catalog="db_assigment" )
public class Customers implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Customer_ID", nullable=false)
    private Integer customerId ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="Customer_Name", length=255)
    private String customerName ;     @Column(name="Customer_Address", length=45)
    private String customerAddress ;     @Column(name="Other_Details", length=45)
    private String otherDetails ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Customers() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setCustomerId(Integer customerId) {
        this.customerId = customerId ;
    }
	public Integer getCustomerId() {
        return this.customerId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : Customer_Name (VARCHAR) 
	public void setCustomerName(String customerName) {this.customerName = customerName;}
	public String getCustomerName() {return this.customerName;}

	//--- DATABASE MAPPING : Customer_Address (VARCHAR) 
	public void setCustomerAddress(String customerAddress) {this.customerAddress = customerAddress;}
	public String getCustomerAddress() {return this.customerAddress;}

	//--- DATABASE MAPPING : Other_Details (VARCHAR) 
	public void setOtherDetails(String otherDetails) {this.otherDetails = otherDetails;}
	public String getOtherDetails() {return this.otherDetails;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(customerId); 
		sb.append(customerName); 
		sb.append("|"); 
		sb.append(customerAddress); 
		sb.append("|"); 
		sb.append(otherDetails); 
        return sb.toString();
    }
}