/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:15:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.ChargeCodes;
import org.demo.repository.ChargeCodesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class ChargeCodesServiceImpl implements ChargeCodesService {

	@Autowired
	private ChargeCodesRepository chargeCodesRepository;

	@Override
	public ChargeCodes getOne(Integer chargeCode) {
		return chargeCodesRepository.getOne(chargeCode);
	}

	@Override
	public Boolean delete(Integer chargeCode) {
		if (chargeCodesRepository.getOne(chargeCode) != null) {
			chargeCodesRepository.deleteById(chargeCode);
			return true;
		}
		return false;
	}

	@Override
	public ChargeCodes create(ChargeCodes chargeCodes) {
		return chargeCodesRepository.save(chargeCodes);
	}

	@Override
	public ChargeCodes update(ChargeCodes chargeCodesToUpdate) {
		ChargeCodes chargeCodes = chargeCodesRepository.getOne(chargeCodesToUpdate.getChargeCode());

		if (chargeCodesToUpdate.getChargeDescription() != null) {

		}
		return chargeCodesRepository.save(chargeCodes);
	}

	@Override
	public Boolean exist(ChargeCodes chargeCodes) {
		return chargeCodesRepository.existsById(chargeCodes.getChargeCode());
	}

	@Override
	public List<ChargeCodes> findAll() {
		return chargeCodesRepository.findAll();
	}

}
